### ISSUE TITLE
`DatePicker` has locales hardcoded into component

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#1679]
`<DatePicker/>` supports `locale` prop and currently it can be one of ``'en', 'es', 'pt', 'fr', 'de', 'pl', 'it', 'ru', 'ja', 'ko', 'tr', 'sv', 'no', 'nl', 'da'``.

these locales are imported into component https://github.com/wix/wix-style-react/blob/master/src/DatePicker/LocaleUtils.js

this means that even if consumer uses only `en`, component will still contain other locales.
moreover, we should support a way for consumer to supply more locales.

1. [ ] add ability to control what locales end up in a bundle
2. [x] add ability to provide additional, custom locales
3. [ ] this page displays dropdown with more locales than current `DatePicker` supports  https://www.wix.com/dashboard/[metasiteId]/settings need to make `DatePicker` so that it can support all of them

**Comment by nickg-wix** [comment]
### Idea - Refactor DataPicker localization ot use `Intl` API

#### Pros
* remove dependency for data-fns library
* native browser support
* lightweight bundle size
* various languages support

#### Cons
* node has limited `Intl` API support (only English), meaning need to use polyfill in tests
* more logic on our end to construct locales for DayPicker
* `Intl` API support optionally 1 or 3 symbols labels for week days, while current implementation based on 2 symbols.

#### Polyfill

Use [Intl.js](https://github.com/andyearnshaw/Intl.js/) only in Unit tests, also package [intl-locales-supported](https://github.com/yahoo/intl-locales-supported) is needed to properly include the polyfill.

**Comment by shlomitc** [comment]
Soon, we're going to support `dynamic Imports` in our components, so maybe we could just import  requested language, while having a fallback to english.
@argshook - wdyt?

**Comment by argshook** [comment]
> so maybe we could just 

yes, maybe we could just but need to investigate. Last time we investigated it was not possible (hence this issue)

**Comment by shlomitc** [comment]
We plan to rework on all date and time components in the upcoming months, including doing performance optimizations and internationalization.
I'm closing the issue to clean old stuff from the backlog.
