### ISSUE TITLE
`<Page/>` - Issues

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2980]
#### Missing Tests

- [ ] When the window is resized - stretch vertically should update
- [ ] Scroll tests with Tail, or different Header combinations, sizes.
- [ ] Horizontal scroll when the window is less than min-width
- [ ] zIndex: 
  - [ ] `should NOT see components with z-index when they go under a sticky item`
  - [ ] Modal should have higher zIndex than sticky
  - [ ] Modal should have higher zIndex than the minimized header

#### Use renderProps instead of`cloneElement`

See [this issue](https://github.com/wix/wix-style-react/issues/2891)
#### Documentation

- [ ] Storybook: Can't have `2.5 Page Example` folder next to the `2.5 Page`, put all examples inside Page single story
- [x] Add Sticky Example with code

### TODO

- [ ] Deprecate Page.FixedContent in favour of `<Page.Sticky/>`

- [ ] Disable `<Button/>` `trantision all 100ms` (#2958)

**Comment by hepiyellow** [comment]
Split into separate issues.
See project
https://github.com/wix/wix-style-react/projects/19
