### ISSUE TITLE
Documentation QA checklist

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#941]
Go over each component and make sure:

- [ ] Component is in its correct location in storybook with the correct index with respect to the zeplin
- [ ] Component is using autoDocs correctly.
- [ ] Component is using autoExample correctly.
- [ ] Component is using autoTestkitDocs correctly.
