### ISSUE TITLE
Component QA checklist

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#973]
- [ ] Accessibility - Approved by Ben & Neil Osman
- [ ] Tests for accessibility
- [ ] Full test coverage
- [ ] One component in each file
- [ ] Extract base component
- [ ] No inheritance (other than WixComponent)
- [ ] Has all autodocs comments
- [ ] Component has dynamic story using autoExample
